version: "3.9"

volumes:
  mysql_data:
    driver: local
services:


  Reclamation:
    container_name: Reclamation-service-container
    build: .\
    ports:
      - "8035:8035"
    hostname: ReclamationService
    image: "reclamation"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - Eureka

  Evenement:
     container_name: evenement-service-container
     build: .\
     ports:
       - "8089:8089"
     hostname: eventServer
     image: "event-service-image"
     environment:
       - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
       - spring.datasource.url=jdbc:mysql://docker-mysql_1:3306/gestionAgence?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
     depends_on:
       - Eureka
       - docker-mysql_1

  docker-mysql_1:
    image: "mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3307:3306

  Reservation:
    container_name: reservation-service-container
    build: .\
    ports:
      - "8083:8083"
    hostname: reservationServer
    image: "reservation-service-image"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
      - spring.datasource.url=jdbc:mysql://docker-mysql_2:3306/gestionAgence?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - Eureka
      - docker-mysql_2

  docker-mysql_2:
    image: "mysql"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 3306:3306


  Eureka:
    container_name: erukaserver-container
    build: .\eurekaServer
    ports:
      - "8761:8761"
    hostname: eurekaServer
    image: "eurekaserver"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:8761/eureka/

  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: molka
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8080:8080
    depends_on:
      - mysql